// Canonical audit library — seeded into library_heads / library_items on first run.
// Source: HTML prototype LIBRARY constant. D-section heads default out-of-scope.
export const AUDIT_LIBRARY = [
  { id: "A::General Information", section: "A", sub: "General Information", items: [
    { ref: "A-1", p: "NTN and SECP registration number", req: true },
    { ref: "A-2", p: "Client contact person — name and mobile number", req: true },
    { ref: "A-3", p: "If a subsidiary — name of the parent company", req: true },
  ]},
  { id: "A::Customer Due Diligence / Know Your Client (CDD / KYC)", section: "A", sub: "Customer Due Diligence / Know Your Client (CDD / KYC)", items: [
    { ref: "A-4", p: "Form A and Form 9", req: true },
    { ref: "A-5", p: "Verify names of directors against the prescribed sheets issued by ICAP", req: false },
  ]},
  { id: "A::Key Relationships", section: "A", sub: "Key Relationships", items: [
    { ref: "A-6", p: "Purchases — party wise", req: true },
    { ref: "A-7", p: "Sales — party wise", req: true },
    { ref: "A-8", p: "List of bank accounts", req: true },
    { ref: "A-9", p: "Loan agreements — including all details", req: true },
    { ref: "A-10", p: "Related parties", req: true },
    { ref: "A-11", p: "Other relationships, if any", req: true },
  ]},
  { id: "A::Important Documents", section: "A", sub: "Important Documents", items: [
    { ref: "A-12", p: "Memorandum and Articles of Association (MOA / AOA)", req: true },
    { ref: "A-13", p: "Certificate of incorporation", req: true },
    { ref: "A-14", p: "Business profile", req: true },
    { ref: "A-15", p: "Group structure", req: true },
    { ref: "A-16", p: "Prior year financial statements and annual return", req: true },
    { ref: "A-17", p: "Contracts and agreements", req: true },
  ]},
  { id: "B::Client Acceptance and Continuance Procedures", section: "B", sub: "Client Acceptance and Continuance Procedures", items: [
    { ref: "B-1", p: "Signed engagement letter", req: true },
    { ref: "B-2", p: "Attach other documents such as letter of arrangement, letter of planning, correspondence, etc., if applicable", req: true },
  ]},
  { id: "B::Auditor Appointment / Change", section: "B", sub: "Auditor Appointment / Change", items: [
    { ref: "B-3", p: "Contact the previous auditor and document the communication", req: false },
    { ref: "B-4", p: "Statutory resignation / appointment formalities", req: false },
  ]},
  { id: "B::Initial Meeting with Client", section: "B", sub: "Initial Meeting with Client", items: [
    { ref: "B-5", p: "Document the matters discussed in the prescribed format (refer Annexure 1)", req: false },
  ]},
  { id: "B::Independence Questionnaire", section: "B", sub: "Independence Questionnaire", items: [
    { ref: "B-6", p: "Attach the independence questionnaire of each individual team member", req: false },
  ]},
  { id: "B::Risk Assessment Procedures and Development of the Audit Strategy", section: "B", sub: "Risk Assessment Procedures and Development of the Audit Strategy", items: [
    { ref: "B-7", p: "Attach the ownership and governance structure", req: true },
    { ref: "B-8", p: "Attach the management structure", req: true },
    { ref: "B-9", p: "Attach the financing structure", req: true },
    { ref: "B-10", p: "Describe the type of investments the entity holds", req: false },
    { ref: "B-11", p: "Specify the laws and regulations that have a fundamental effect on the operations of the entity (refer Annexure 2)", req: false },
    { ref: "B-12", p: "Identify and list the accounting estimates used by the entity in preparing the financial statements (refer Annexure 3)", req: false },
    { ref: "B-13", p: "Identify and document the related parties of the entity and the type of transactions entered into with them (refer Annexure 4)", req: false },
    { ref: "B-14", p: "Document any significant developments during the period", req: false },
  ]},
  { id: "B::Understanding the Entity's Internal Controls", section: "B", sub: "Understanding the Entity's Internal Controls", items: [
    { ref: "B-15", p: "Document the information systems in use (refer Annexure 5)", req: false },
  ]},
  { id: "B::Identifying and Assessing the Risk", section: "B", sub: "Identifying and Assessing the Risk", items: [
    { ref: "B-16", p: "Review the statutory records required to be maintained by the entity under the applicable Acts; attach a copy of the summary prepared", req: false },
    { ref: "B-17", p: "Prepare a summary of the minutes of the meetings of the Board of Directors", req: false },
    { ref: "B-18", p: "Obtain a confirmation from management on the completeness of the meeting minutes", req: false },
  ]},
  { id: "B::Analytical Reviews", section: "B", sub: "Analytical Reviews", items: [
    { ref: "B-19", p: "Review all account heads of the statement of financial position and the profit and loss account, and record the analytical review against each head", req: false },
  ]},
  { id: "B::Fraud Risk Assessment", section: "B", sub: "Fraud Risk Assessment", items: [
    { ref: "B-20", p: "Document the matters discussed in the prescribed format (refer Annexure 6)", req: false },
  ]},
  { id: "B::Establishing the Overall Audit Strategy", section: "B", sub: "Establishing the Overall Audit Strategy", items: [
    { ref: "B-21", p: "Engagement team and budget — allocate the team and record the budgeted hours", req: false },
    { ref: "B-22", p: "Update the staff and partner names in the software", req: false },
    { ref: "B-23", p: "Engagement team meeting — document the matters discussed (refer Annexure 7)", req: false },
  ]},
  { id: "C::Opening Balances", section: "C", sub: "Opening Balances", items: [
    { ref: "C-1", p: "Prepare the test documentation for opening balances", req: false },
    { ref: "C-2", p: "Test a sample of opening balance entries in the prescribed format (refer Annexure 8)", req: true },
  ]},
  { id: "C::Estimates and Judgements", section: "C", sub: "Estimates and Judgements", items: [
    { ref: "C-3", p: "Prepare the test documentation of estimates and judgements in the prescribed format (refer Annexure 9)", req: false },
  ]},
  { id: "C::Unusual Transactions", section: "C", sub: "Unusual Transactions", items: [
    { ref: "C-4", p: "Prepare the test documentation of unusual transactions, if any", req: false },
  ]},
  { id: "C::Journal Entries and Other Adjustments", section: "C", sub: "Journal Entries and Other Adjustments", items: [
    { ref: "C-5", p: "Prepare the test documentation of journal entries in the prescribed format (refer Annexure 10)", req: false },
  ]},
  { id: "C::General IT Controls (GITC)", section: "C", sub: "General IT Controls (GITC)", items: [
    { ref: "C-6", p: "Document the IT application process and the related audit procedures (refer Annexure 11)", req: false },
    { ref: "C-7", p: "Based on the control testing, document the responses to the assessed GITC risks (refer Annexure 12)", req: false },
  ]},
  { id: "C::Using the Work of the Internal Auditor", section: "C", sub: "Using the Work of the Internal Auditor", items: [
    { ref: "C-8", p: "Evaluate the threats to the objectivity of the internal auditors and the level of competence of the internal auditors used to provide direct assistance (refer Annexure 13)", req: false },
    { ref: "C-9", p: "Determine the nature and extent of the work of the internal audit function that can be used (refer Annexure 14)", req: false },
  ]},
  { id: "C::Written Representation", section: "C", sub: "Written Representation", items: [
    { ref: "C-10", p: "Obtain the written representation letter from management", req: false },
  ]},
  { id: "D::Property, Plant and Equipment and Intangible Assets", section: "D", sub: "Property, Plant and Equipment and Intangible Assets", items: [
    { ref: "D-1", p: "Developing the audit approach — process flow: understanding of the business cycle, process flow description, accounting entries and walkthrough procedures", req: false },
    { ref: "D-2", p: "Developing the audit approach — perform the audit assertion wise", req: false },
    { ref: "D-3", p: "Detailed listing (fixed asset register) of all property, plant and equipment, by asset group, stating cost and depreciation (asset wise) for the year, along with additions, disposals, write offs and impairment", req: true },
    { ref: "D-4", p: "Additions and disposals schedule with all related details", req: true },
    { ref: "D-5", p: "Invoices for acquisition of assets", req: true },
    { ref: "D-6", p: "Impairment assessment prepared by management", req: true },
    { ref: "D-7", p: "Details of disposals", req: true },
    { ref: "D-8", p: "Revaluation supporting documents / assessment, if any revaluation was carried out during the year", req: true },
    { ref: "D-9", p: "Ascertain whether any asset is pledged or mortgaged and ensure proper disclosure", req: false },
    { ref: "D-10", p: "Test of details — additions and disposals with payment verification from the bank", req: false },
    { ref: "D-11", p: "Test of details — depreciation working", req: false },
    { ref: "D-12", p: "Test of details — held for capital (HFC) items", req: false },
  ]},
  { id: "D::Investment Property", section: "D", sub: "Investment Property", items: [
    { ref: "D-13", p: "Detailed listing (schedule) of all investment properties, along with details of transfers, disposals and impairment recognised during the year", req: true },
    { ref: "D-14", p: "Impairment assessment", req: true },
    { ref: "D-15", p: "Rental agreements", req: true },
    { ref: "D-16", p: "Obtain confirmations from the management on the completeness of the investment property listing and any encumbrances related to the investment properties", req: false },
    { ref: "D-17", p: "Valuation report of the independent valuer", req: true },
    { ref: "D-18", p: "Test of details — additions and disposals with payment verification from the bank", req: false },
  ]},
  { id: "D::Inventories", section: "D", sub: "Inventories", items: [
    { ref: "D-19", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-20", p: "Developing the audit approach — perform the audit assertion wise", req: false },
    { ref: "D-21", p: "Detailed listing of inventories, stating cost and any write-downs to net realisable value (NRV)", req: true },
    { ref: "D-22", p: "Inventory count sheets (signed by the management)", req: true },
    { ref: "D-23", p: "Test of details — inventory count procedures", req: false },
    { ref: "D-24", p: "Inventory costing schedule / cost computation", req: true },
    { ref: "D-25", p: "NRV assessment by management", req: true },
    { ref: "D-26", p: "Inventory turnover analysis (last 3 years)", req: false },
    { ref: "D-27", p: "Slow-moving / obsolete inventory analysis by management", req: true },
  ]},
  { id: "D::Cash and Bank", section: "D", sub: "Cash and Bank", items: [
    { ref: "D-28", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-29", p: "Developing the audit approach — perform the audit assertion wise", req: false },
    { ref: "D-30", p: "Bank statements for all bank accounts, signed and stamped by the bank", req: true },
    { ref: "D-31", p: "Bank reconciliation statement for all bank accounts as at year-end", req: true },
    { ref: "D-32", p: "Bank confirmation letter, addressed to HFC (for each account)", req: true },
    { ref: "D-33", p: "Cash count sheet (signed by management)", req: true },
    { ref: "D-34", p: "List of all bank accounts maintained by the entity", req: true },
    { ref: "D-35", p: "Test of details — bank reconciliation", req: false },
    { ref: "D-36", p: "If any account has unusual items / significant reconciling items — provide the details for each such item", req: true },
  ]},
  { id: "D::Investments", section: "D", sub: "Investments", items: [
    { ref: "D-37", p: "Detailed listing of all investments (quoted and unquoted), stating the cost and fair value", req: true },
    { ref: "D-38", p: "Investment agreements / certificates", req: true },
    { ref: "D-39", p: "Broker / fund manager statements", req: true },
    { ref: "D-40", p: "Confirmations from the investees for unquoted investments", req: true },
    { ref: "D-41", p: "Impairment assessment for unquoted investments", req: true },
    { ref: "D-42", p: "Test of details — valuation of investments", req: false },
  ]},
  { id: "D::Trade and Other Receivables", section: "D", sub: "Trade and Other Receivables", items: [
    { ref: "D-43", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-44", p: "Developing the audit approach — perform the audit assertion wise", req: false },
    { ref: "D-45", p: "Aged debtor analysis (party wise)", req: true },
    { ref: "D-46", p: "Debtor confirmation letters (addressed to HFC)", req: true },
    { ref: "D-47", p: "Test of details — debtor circularisation", req: false },
    { ref: "D-48", p: "ECL / bad debt provision workings", req: true },
    { ref: "D-49", p: "Reconciliation of trade receivables ledger with subsidiary ledger", req: true },
    { ref: "D-50", p: "Sales cut-off documents", req: true },
    { ref: "D-51", p: "Details of any related party receivables", req: true },
    { ref: "D-52", p: "Details of any receivables that are pledged as security", req: true },
    { ref: "D-53", p: "Advances to suppliers schedule", req: true },
    { ref: "D-54", p: "Details of prepayments", req: true },
    { ref: "D-55", p: "Withholding tax reconciliation", req: true },
    { ref: "D-56", p: "Details of other receivables", req: true },
  ]},
  { id: "D::Other Assets", section: "D", sub: "Other Assets", items: [
    { ref: "D-57", p: "Details of other assets not covered above", req: true },
    { ref: "D-58", p: "Supporting documents for other assets", req: true },
  ]},
  { id: "D::Borrowings", section: "D", sub: "Borrowings", items: [
    { ref: "D-59", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-60", p: "Schedule of all borrowings (long-term and short-term), including opening balance, drawdowns, repayments and closing balance", req: true },
    { ref: "D-61", p: "Loan agreements for all borrowings", req: true },
    { ref: "D-62", p: "Bank / lender confirmation letter (addressed to HFC)", req: true },
    { ref: "D-63", p: "Interest computation / schedule", req: true },
    { ref: "D-64", p: "Covenant compliance certificate / details", req: true },
    { ref: "D-65", p: "Details of any assets pledged as security for borrowings", req: true },
    { ref: "D-66", p: "Details of any default or breach of covenants during the year", req: true },
    { ref: "D-67", p: "Test of details — borrowings movement", req: false },
  ]},
  { id: "D::Trade and Other Payables", section: "D", sub: "Trade and Other Payables", items: [
    { ref: "D-68", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-69", p: "Aged creditor analysis (party wise)", req: true },
    { ref: "D-70", p: "Creditor confirmation letters (addressed to HFC)", req: true },
    { ref: "D-71", p: "Test of details — creditor circularisation", req: false },
    { ref: "D-72", p: "Reconciliation of trade payables ledger with supplier statements", req: true },
    { ref: "D-73", p: "Purchases cut-off documents", req: true },
    { ref: "D-74", p: "Details of any related party payables", req: true },
    { ref: "D-75", p: "Accruals schedule with supporting", req: true },
    { ref: "D-76", p: "Advances from customers schedule", req: true },
    { ref: "D-77", p: "Details of other payables", req: true },
  ]},
  { id: "D::Income Tax", section: "D", sub: "Income Tax", items: [
    { ref: "D-78", p: "Tax computation for the year (current and deferred)", req: true },
    { ref: "D-79", p: "Tax return filed for the year", req: true },
    { ref: "D-80", p: "Tax demand notice / assessment order, if any", req: true },
    { ref: "D-81", p: "Deferred tax reconciliation", req: true },
    { ref: "D-82", p: "Withholding tax statements", req: true },
    { ref: "D-83", p: "Tax advice / legal opinion on disputed matters, if any", req: true },
    { ref: "D-84", p: "Advance tax / tax refund details", req: true },
    { ref: "D-85", p: "Test of details — income tax computation", req: false },
  ]},
  { id: "D::Provisions, Contingent Liabilities and Financial Commitments", section: "D", sub: "Provisions, Contingent Liabilities and Financial Commitments", items: [
    { ref: "D-86", p: "Schedule of all provisions, contingent liabilities and financial commitments", req: true },
    { ref: "D-87", p: "Legal / expert opinion on pending litigation and claims", req: true },
    { ref: "D-88", p: "Confirmation from legal counsel on outstanding litigation", req: true },
    { ref: "D-89", p: "Capital commitments schedule with supporting contracts", req: true },
    { ref: "D-90", p: "Operating lease commitments schedule", req: true },
    { ref: "D-91", p: "Details of any other contingent liabilities or commitments", req: true },
  ]},
  { id: "D::Sales / Revenue", section: "D", sub: "Sales / Revenue", items: [
    { ref: "D-92", p: "Developing the audit approach — process flow", req: false },
    { ref: "D-93", p: "Developing the audit approach — perform the audit assertion wise", req: false },
    { ref: "D-94", p: "Sales / revenue schedule (product-wise / segment-wise)", req: true },
    { ref: "D-95", p: "Sales ledger", req: true },
    { ref: "D-96", p: "Sales tax returns (monthly)", req: true },
    { ref: "D-97", p: "Sales invoices (on a sample basis)", req: true },
    { ref: "D-98", p: "Dispatch / delivery notes (on a sample basis)", req: true },
    { ref: "D-99", p: "Credit notes / returns schedule", req: true },
    { ref: "D-100", p: "Revenue recognition policy and basis of recognition", req: true },
    { ref: "D-101", p: "Sales cut-off documents", req: true },
    { ref: "D-102", p: "Customer contracts (for significant customers)", req: true },
    { ref: "D-103", p: "Test of details — revenue", req: false },
  ]},
  { id: "D::Cost of Sales", section: "D", sub: "Cost of Sales", items: [
    { ref: "D-110", p: "Cost of sales schedule", req: true },
    { ref: "D-111", p: "Cost of sales ledger", req: true },
    { ref: "D-112", p: "Inventory movement report", req: true },
    { ref: "D-113", p: "Inventory valuation workings", req: true },
    { ref: "D-114", p: "Purchase invoices (on a sample basis)", req: true },
    { ref: "D-115", p: "Goods received notes (GRNs)", req: true },
    { ref: "D-116", p: "Purchases cut-off documents", req: true },
    { ref: "D-117", p: "Prepare the test of details of purchases", req: false },
  ]},
  { id: "D::Expenses — Selling / Administrative / Finance", section: "D", sub: "Expenses — Selling / Administrative / Finance", items: [
    { ref: "D-118", p: "Detailed listing of expenses by nature (administrative, marketing, finance costs, etc.) incurred during the year", req: true },
    { ref: "D-119", p: "Expense ledgers", req: true },
    { ref: "D-120", p: "Copies of all contracts entered into with vendors, rental agreements, marketing agreements and related computations", req: true },
    { ref: "D-121", p: "Payroll register / salary sheets and interest and rent documents", req: true },
    { ref: "D-122", p: "Payments to management (directors' remuneration)", req: true },
    { ref: "D-123", p: "Expense vouchers", req: true },
    { ref: "D-124", p: "Payment verification", req: false },
    { ref: "D-125", p: "Cut-off documents", req: true },
    { ref: "D-126", p: "Bank payment evidence", req: false },
    { ref: "D-127", p: "Prepare the test of details for all categories of expenses (salaries, utilities, travelling, etc.)", req: false },
  ]},
  { id: "D::Other Income", section: "D", sub: "Other Income", items: [
    { ref: "D-128", p: "Other income schedule", req: true },
    { ref: "D-129", p: "Other income ledgers", req: true },
    { ref: "D-130", p: "Bank profit certificates", req: true },
    { ref: "D-131", p: "Dividend warrants", req: true },
    { ref: "D-132", p: "Rental agreements", req: true },
    { ref: "D-133", p: "Gain / loss on disposal workings", req: false },
    { ref: "D-134", p: "Foreign exchange gain / loss workings", req: false },
    { ref: "D-135", p: "Supporting invoices / receipts", req: true },
  ]},
];

export const SECTION_NAMES = {
  A: "A · Permanent File",
  B: "B · Planning File",
  C: "C · General Procedures",
  D: "D · Head-Wise Audit",
};

// D-section heads are opt-in per client; A/B/C default included.
export const defaultIncluded = (section) => section !== "D";
